### ISSUE TITLE
run_dev.sh fails on ros2bag

### ISSUE THREAD

**Issue by robomike** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#10]
- Fresh install of ubuntu 20.04 on desktop computer
- Fresh install of ros2-humble
- fresh install of nvidia container toolkit
- fresh install of omniverse sim

followed [install instructions.](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_apriltag)

Got error:
Finished <<< rosbag2_py [44.0s]
Starting >>> ros2bag
Finished <<< nav2_map_server [1min 17s]
Finished <<< ros2bag [21.3s]
Starting >>> rosbag2_tests
--- stderr: ros2bag
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
The command '/bin/bash -c cd ${ROS_ROOT}       && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo --packages-up-to behaviortree_cpp_v3       && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo       && rm -Rf src build log' returned a non-zero code: 137
Failed to build base image: isaac_ros_dev-x86_64, aborting.
~/workspaces/isaac_ros-dev/src/isaac_ros_common

**Comment by hemalshahNV** [comment]
Was there anything else in the log? The warning there from install.py is just a warning.

**Comment by hemalshahNV** [comment]
No, but there are unanchored dependencies which could have changed. Could you provide the entire log? The reason for the failure is not clear in the snippets so far.

**Comment by hemalshahNV** [comment]
Please try running with updated isaac_ros_common release which uses prebuilt images for ROS2 Humble which will let you avoid all of the building.
