### ISSUE TITLE
Is tagStandard41h12 supported?

### ISSUE THREAD

**Issue by Hiroaki-K4** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#12]
Hi, thanks for publishing the code.
The link below says this, but is there any change in the types of tags that are still supported?
`In the 2018.3 release, the tag36h11 tag family is supported. Extending the algorithm to other tag families is planned for a future release.`
https://docs.nvidia.com/isaac/packages/fiducials/doc/apriltags.html
I would like to know if tagStandard41h12 is supported.

**Comment by hemalshahNV** [comment]
No, we have not extended support for more tag families beyond tag36h11. Is there any particular reason you wanted to use tag family 41h12 though?

**Comment by Hiroaki-K4** [comment]
Thank you for reply.
There is no particular reason. I will also consider changing the tag type.
