### ISSUE TITLE
Jetson Xavier NX High CPU Usage

### ISSUE THREAD

**Issue by trentatsa** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#13]
Hi there, I followed all steps in order to run this package within the provided ROS humble docker using Jetpack 5.0.1 on a Jetson Xavier NX and all is working as should however, my CPU usage is 200% which defeats the point of using isaac_apriltag package in the first place as the CPU based packages usage is on a order of magnitude less. 
Is this normal and if not what could be the problem ? 

Thanks for your help!

**Comment by hemalshahNV** [comment]
This is unexpected as there really is no significant code in isaac_ros_apriltag that executes on CPU. Is there anything else running on the NX? Running [`jtop`](https://github.com/rbonghi/jetson_stats) might give us some insight into what's eating up the CPUs. Could you post the launch file perhaps you're using to try out isaac_ros_apriltag which shows the camera node being used? We'll attempt to reproduce this on an NX in the meantime.

**Comment by trentatsa** [comment]
@hemalshahNV appreciate you looking into it. By 200% I meant the isaac-apriltag package is using 200% CPU within the docker. Looking forward to seeing what you can find :)

**Comment by trentatsa** [comment]
Hi @hemalshahNV , any progress on reproducing the issue ?

**Comment by hemalshahNV** [comment]
We can reproduce `top` claiming CPU utilization of over 200% on an NX, AGX, and even x86 while running any of our packages it seems, but this doesn't seem to be an accurate characterization. The %cpu at the top for 13.3 us/user is more accurate, 84% id/idle). The CPU utilization shown for a process is per CPU, not core: ([link](https://superuser.com/questions/174660/why-is-the-cpu-usage-reported-by-top-in-linux-over-100#:~:text=Yes%2C%20if%20a%20process%20in,core%20than%20is%20phsyically%20manageble)). The ROS2 process is consuming time on the cores of one CPU, leaving 7 remaining idle on the NX. When running with `jtop` and other sysstat utilities in our benchmark framework for isaac_ros_apriltag, we don't see overall CPU usage of more than 15-30% which is more consistent with what we would expect.
