### ISSUE TITLE
Support for Multi-Camera(s) ?

### ISSUE THREAD

**Issue by HappySamuel** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#14]
Hi

Does isaac_ros_apriltag support multi-camera(s) ? 
If does, how much camera(s) can it support at the same time ? 
How shall i config the parameters for different camera(s) ?
As my robot has 4 camera(s), front, left, right, rear.

Best,
Samuel

**Comment by hemalshahNV** [comment]
You'd want to run 4 separate instances of the Apriltag node to detect fiducials in each of the cameras separately. Apriltag pose estimation is intended to work with individual frames from a monocular camera and doesn't really have a multi-camera application unless you had something else in mind.

**Comment by HappySamuel** [comment]
Hi @hemalshahNV 

Thanks for the guidance, i will try out the separate instances of Apriltag node(s) for each camera(s).

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @hemalshahNV 

Will there be any multi-cameras support for this isaac_ros_apriltag, similar to other isaac_ros packages, currently all support multi-cameras on the latest release 3.0.1

Best,
Samuel

**Comment by hemalshahNV** [comment]
Hi, Samuel. We don't have any plans to support multi-camera AprilTag detection yet, no, but how did you envision it would work? If it is just tracking a tag across cameras, you should be able to do that by tracking the pose of a tag relative to say a camera rig frame. Were you thinking of using overlapping fields of view to get a more accurate estimation perhaps?
