### ISSUE TITLE
Cuda Error after I change output size to 1280x720.

### ISSUE THREAD

**Issue by lymnxn** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#18]
Hello:
I use a IMX219 Camera, it can output in 1280x720, So I change rectify_node output size to 1280x720, and get error:

[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:97 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_x2, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:98 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_y2, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:99 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_xy, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:100 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_x2, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:101 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_y2, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:102 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_xy, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:104 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_maxima_suppression, sizeof(bool) * corners_w * corners_h)" 
[component_container_mt-1] CUDA error at external/libapriltag/april_tagging/corner_detection/corner_detector.cpp:187 code=700(cudaErrorIllegalAddress) "cudaStreamWaitEvent(x2_stream, sync_event_x2, 0)"

**Comment by hemalshahNV** [comment]
What platform are you running this on (x86_64 w/ GPU or Jetson, in or outside of Isaac ROS Dev base container)? At first glance, it seems AprilTag ran out of GPU memory. Have you tried at smaller resolutions just to see if it works at all?

**Comment by lymnxn** [comment]
> What platform are you running this on (x86_64 w/ GPU or Jetson, in or outside of Isaac ROS Dev base container)? At first glance, it seems AprilTag ran out of GPU memory. Have you tried at smaller resolutions just to see if it works at all?

I use on Jetson Xavier NX 8G Version, CSI IMX219 Camera. In the container.

**Comment by hemalshahNV** [comment]
Is there anything else running with the Apriltag node that could be eating up GPU memory perhaps?

**Comment by nakai-omer** [comment]
@hemalshahNV We are also experiencing this issue with similar camera:
```
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:84 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_normalized_input_image, size_t(sizeof(float) * image_w * image_h))" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:97 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_x2, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:98 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_y2, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:99 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_gradient_xy, sizeof(float) * gradient_w * gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:100 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_x2, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:101 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_y2, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:102 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_blur_gradient_xy, sizeof(float) * blur_gradient_w * blur_gradient_h)" 
[component_container_mt-1] CUDA error at /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/corner_detection/corner_detector.cpp:104 code=2(cudaErrorMemoryAllocation) "cudaMalloc((void**)&d_maxima_suppression, sizeof(bool) * corners_w * corners_h)" 
[component_container_mt-1] component_container_mt: /workspaces/isaac_ros-dev/lib/src/nvapriltags/april_tagging/april_tag.cpp:20: void AprilTags::DetectAndDecodeAprilTags(const DeviceDataView<uchar3>&, cuAprilTagsID_t*, SizeT*, SizeT, cudaStream_t): Assertion `input_image.size_.x == w && input_image.size_.y == h' failed.
```
