### ISSUE TITLE
realsense support ? jammy support? neither?

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#19]
is it possible to use with reealsense d400 camera? 
with OS upgraded to jammy?
both? neither of the two ?

**Comment by AndreV84** [comment]
@gordongrigor could you extend, how exactly did you run nvidia ros apriltags  , please?
using isaac_ros_apriltag package? the one that is dockerized with humble focal environment? if so how did you run realsense node on it? otherwise which other environment have you used?

**Comment by gordongrigor** [comment]
Guidance you are looking for is provided online tutorials.

https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_apriltag/blob/main/docs/tutorial-usb-cam.md

**Comment by AndreV84** [comment]
@gordongrigor 
Thank you for your response. 
Could you extend if it  [ https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md ]is applicable to this current nvidia apriltags humble focal container release. please? or you had in mind other ros like foxy when pointed to the url?

**Comment by AndreV84** [comment]
folks point out that running container every time utilizes the run_dev script which is very time consuming as it rebuilds everything on startup in a way you published it it is very slow on startup as a result
is there any easy fix for it so second and consequent runs are fast?

**Comment by hemalshahNV** [comment]
When launching the Isaac ROS Dev base container, it runs `rosdep --install` to make sure you have all of the packages for your specific ROS workspace available. Second and subsequent invocations of `run_dev.sh` will attach to the same launched container rather than launching a new one and should be instantaneous.

**Comment by AndreV84** [comment]
we were able to use the instruction on AGX Jetson Xavier 5.0.2 in a way the realsense camera worked with apriltags or nvblox integration as it seems
However trying right now to implement it on AGX Orin devkit
the build of the container gets stuck at building realsense step
```

-- Configuring incomplete, errors occurred!
See also "/root/librealsense/build/CMakeFiles/CMakeOutput.log".
See also "/root/librealsense/build/CMakeFiles/CMakeError.log".
Building librealsense, headers, tools and demos
make: *** No targets specified and no makefile found.  Stop.

real    0m0.002s
user    0m0.000s
sys     0m0.002s
librealsense did not build 
Retrying ... 
make: *** No targets specified and no makefile found.  Stop.

real    0m0.002s
user    0m0.002s
sys     0m0.000s
librealsense did not successfully build
Please fix issues and retry build
The command '/bin/bash -c chmod +x /opt/realsense/build-librealsense.sh && /opt/realsense/build-librealsense.sh' returned a non-zero code: 1
Failed to build base image: isaac_ros_dev-aarch64, aborting.
```

**Comment by hemalshahNV** [comment]
@AndreV84 , could you post more of the log where build-librealsense.sh failed? It isn't clear why building librealsense from source failed but it might be something else missing. We have not seen this yet locally but our setup may be different than yours.
