### ISSUE TITLE
TF_NO_FRAME_ID

### ISSUE THREAD

**Issue by BBlumhofer** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#20]
When I try to run April Tag detection, the following error is logged: 

`Error:   TF_NO_FRAME_ID: Ignoring transform with child_frame_id "tag36h11:9"  from authority "Authority undetectable" because frame_id not set`

For detection, I am using a ZED2 to convert the image encoding and then sending reading of the image in the April tag detection from Isaac ROS. The ZED2 is running in another Docker, but the containers can communicate.

**Comment by hemalshahNV** [comment]
Can you confirm that the images coming out of the ZED2 have a frame_id populated in their header? This error can happen when the Apriltag detector publishes a tf transform between the camera frame_id (taken from the image's header) and the tag frame (<tag family>:<id>). If the camera frame_id is empty, then tf2 will be upset that the detector tried publishing a transform between nothing and a tag.

**Comment by BBlumhofer** [comment]
Oh, thanks for the help. I missed publishing the frame id on my converter. The issue can be closed! Thanks a lot.
