### ISSUE TITLE
Is it possible to use ros1_bridge to communicate with ros1 nodes?

### ISSUE THREAD

**Issue by yijh0611** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#29]
Hello, I would like to subscribe to the tf of AprilTag from a ROS1 node. As this library is wrapped in ROS2, I attempted to install the ros1_bridge package from this [GitHub](https://github.com/ros2/ros1_bridge/) page. However, an error occurred during the package build. From my research, it seems that this package is intended to be used with ROS2 Foxy. I am wondering if it is possible to install and use the ros1_bridge package with this library, or if I need to reinstall ROS2 Humble in a seperate docker container in order to use this package?

**Comment by jaiveersinghNV** [comment]
At the moment, we test all of our packages exclusively on ROS 2 Humble. Many of our Isaac ROS packages, including Isaac ROS AprilTag, depend on new features added in the ROS 2 Humble release to support [NITROS](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros) type adaptation for fast message communication between nodes. As a result, our packages won't run on ROS 2 Foxy. 

Your best bet may be to adapt the `ros1_bridge` package to work on ROS 2 Humble. If you choose to use the Docker container approach, note that we provide Isaac ROS Docker containers with ROS 2 Humble prebuilt as part of [Isaac ROS Common](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common).

Please let us know if you're able to get this working :)

**Comment by jaiveersinghNV** [comment]
In the latest Isaac ROS 2.0 release, we've added support for the [Isaac ROS NITROS Bridge](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_nitros_bridge/index.html) to support connecting Isaac ROS nodes with ROS 1 nodes.

In fact, we have an [Isaac ROS AprilTag NITROS Bridge tutorial](https://nvidia-isaac-ros.github.io/concepts/fiducials/apriltag/tutorial_apriltag_ros1_bridge.html) that addresses your exact use case.

Hope this helps!
