### ISSUE TITLE
Cuda failure: Unable to recieve meaningful tag_detections

### ISSUE THREAD

**Issue by nsr-taylor** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#3]
I am getting a strange error message while running 'ros2 run isaac_ros_apriltag isaac_ros_apriltag':

![Screenshot from 2022-02-04 11-02-14](https://user-images.githubusercontent.com/97251418/153301254-6b1c0798-df02-4e6d-886d-78ba2b04668c.png)

This error message only appears after I spin up the calibrated camera publisher, as instructed in Step 6 of the Quickstart section. For reference, I am using the v4l2_camera node, which is compatible with my laptop camera. This error is especially confusing as the path '/home/thomas/Downloads' doesn't exist on my local machine or in the docker container. Likewise, I am unable to receive meaningful /tag_detections information, as I'm not sure that the isacc_ros_apriltag node is publishing anything given the issue raised above.

I am running the docker container on x86_64 and meet all of the outlined system requirements. I have been able to successfully get the isaac_ros_image_pipeline to work, which leads me to believe that my container workspace has been setup correctly.

Any help would be greatly appreciated. Please let me know if I failed to mention any information that would prove valuable in getting this issue resolved. Thanks in advance!

**Comment by ctxqlxs** [comment]
focus

**Comment by ctxqlxs** [comment]
Static link library is not suitable for 30 * Series graphics card？

**Comment by hemalshahNV** [comment]
We need to check that the Apriltag GPU code has been compiled for Ampere architecture (RTX 30-series).

**Comment by ctxqlxs** [comment]
@hemalshahNV  will the Apriltag GPU code release ?

**Comment by hemalshahNV** [comment]
The EA3 release in March 2022 updated the AprilTag tag detector code to run on Ampere-based RTX 30x series cards.
