### ISSUE TITLE
Latest version does not run on Jetpack 5.1.2 [L4T 35.4.1] Orin-AGX

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#41]
Iam trying the quickstart example of isaac_ros_apriltags. I get the following error. Other applications (e.g. Visual Slam etc ) are working fine. Any help would be appreciated.
Thank you
Sandeep
admin@orin-agx:/workspaces/isaac_ros_stuff/src/isaac_ros_apriltag$ ros2 launch isaac_ros_apriltag isaac_ros_apriltag.launch.py
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-11-07-11-13-56-737337-orin-agx-9145
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container_mt-1]: process started with pid [9157]
[component_container_mt-1] [INFO] [1699384437.267629942] [apriltag_container]: Load Library: /workspaces/isaac_ros_stuff/install/isaac_ros_apriltag/lib/libapriltag_node.so
[component_container_mt-1] [INFO] [1699384437.347700828] [apriltag_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::apriltag::AprilTagNode>
[component_container_mt-1] [INFO] [1699384437.347889501] [apriltag_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::apriltag::AprilTagNode>
[component_container_mt-1] [INFO] [1699384437.373393666] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container_mt-1] [INFO] [1699384437.373708964] [apriltag]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1699384437.376281845] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container_mt-1] [INFO] [1699384437.385640529] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container_mt-1] [INFO] [1699384437.391190165] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container_mt-1] [INFO] [1699384437.397244956] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container_mt-1] [INFO] [1699384437.403127010] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros_stuff/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container_mt-1] [INFO] [1699384437.404568108] [NitrosContext]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1699384437.408508005] [NitrosContext]: [NitrosContext] Running application...
[component_container_mt-1] 2023-11-07 11:13:57.408 WARN  gxf/std/program.cpp@514: No system specified. Nothing to do
[component_container_mt-1] [INFO] [1699384437.415157584] [apriltag]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1699384437.415304401] [apriltag]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1699384437.418362245] [apriltag]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1699384437.418494182] [apriltag]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1699384437.419833487] [apriltag]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1699384437.419894159] [apriltag]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1699384437.420490643] [apriltag]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1699384437.421806203] [apriltag]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container_mt-1] [INFO] [1699384437.425626260] [apriltag]: [NitrosContext] Loading extension: gxf/lib/multimedia/libgxf_multimedia.so
[component_container_mt-1] [INFO] [1699384437.427972291] [apriltag]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container_mt-1] [INFO] [1699384437.434093323] [apriltag]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container_mt-1] [INFO] [1699384437.438921290] [apriltag]: [NitrosContext] Loading extension: gxf/lib/libgxf_isaac_messages.so
[component_container_mt-1] [INFO] [1699384437.442668098] [apriltag]: [NitrosContext] Loading extension: gxf/lib/image_proc/libgxf_tensorops.so
[component_container_mt-1] [INFO] [1699384437.453629353] [apriltag]: [NitrosContext] Loading extension: gxf/lib/fiducials/libgxf_fiducials.so
[component_container_mt-1] [INFO] [1699384437.461641021] [apriltag]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1699384437.466384572] [apriltag]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1699384437.586187075] [apriltag]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1699384437.592111849] [apriltag]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1699384437.616075428] [apriltag]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/apriltag' in container '/apriltag_container'
[component_container_mt-1] [INFO] [1699384438.618039766] [apriltag]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1699384438.618306327] [apriltag]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1699384438.618399224] [apriltag]: [NitrosPublisher] Negotiation ended with no results
[component_container_mt-1] [INFO] [1699384438.618474073] [apriltag]: [NitrosPublisher] Use only the compatible publisher: topic_name="/tag_detections", data_format="nitros_april_tag_detection_array"
[component_container_mt-1] [INFO] [1699384438.618540633] [apriltag]: [NitrosSubscriber] Negotiation ended with no results
[component_container_mt-1] [INFO] [1699384438.618592825] [apriltag]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/camera_info", data_format="nitros_camera_info"
[component_container_mt-1] [INFO] [1699384438.618642426] [apriltag]: [NitrosSubscriber] Negotiation ended with no results
[component_container_mt-1] [INFO] [1699384438.618687482] [apriltag]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/image", data_format="nitros_image_bgr8"
[component_container_mt-1] [INFO] [1699384438.619040572] [apriltag]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1699384438.644939460] [apriltag]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros_stuff/install/isaac_ros_apriltag/share/isaac_ros_apriltag/WRMOYBTIKU.yaml"
[component_container_mt-1] [INFO] [1699384438.645148389] [apriltag]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1699384438.645216678] [apriltag]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1699384438.645290694] [apriltag]: [NitrosContext] Loading application: '/workspaces/isaac_ros_stuff/install/isaac_ros_apriltag/share/isaac_ros_apriltag/WRMOYBTIKU.yaml'
[ERROR] [component_container_mt-1]: process has died [pid 9157, exit code -11, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container_mt --ros-args -r __node:=apriltag_container -r __ns:=/'].

**Comment by hemalshahNV** [comment]
Nothing suspicious from the logs until the process died unceremoniously. Could you describe more about your setup? Jetson AGX Orin running Jetpack 5.1.2. Any other details that may be relevant?

**Comment by sandeepdutta** [comment]
It is running on a container from jetson-containers with ros:humble-desktop zed  .. 
All the other isaac_ros functions work ok... any ideas on what more information  I can provide.

**Comment by hemalshahNV** [comment]
Could you try running the example in the Isaac ROS Dev base container [here](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_common/index.html)? It is possible some environment variable or package is not installed in jetson-containers as we have not verified under this container.

**Comment by sandeepdutta** [comment]
Sorry for the delay, I tried in the isaac_ros_common container and it works ... closing it
