### ISSUE TITLE
sudo apt-get install -y ros-humble-isaac-ros-apriltag

### ISSUE THREAD

**Issue by weirdsim14** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#43]
sudo apt-get install -y ros-humble-isaac-ros-apriltag

[sudo] password for sim: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-isaac-ros-apriltag

**Comment by jaiveersinghNV** [comment]
Could you please confirm the following:
1. Are you running this command inside the Isaac ROS Dev Docker container? The Dockerfile we provide as part of Isaac ROS Common automatically adds the Isaac ROS apt repository to the sources list, which is a prerequisite to being able to download the Debian packages.
2. Are you using the latest version of Isaac ROS? Isaac ROS Debian packages were initially made available with the Isaac ROS 2.1 release
3. Does your device have a stable connection to the internet? To test if your device is able to fetch the latest sources, please run:
  ```
  sudo apt-get update
  ```
