### ISSUE TITLE
Error in doing ros2 launch isaac_ros_apriltag isaac_ros_apriltag_usb_cam.launch.py

### ISSUE THREAD

**Issue by conctsai** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#45]
I want to run apriltag by USB camera and I'm entirely followed the guidance in https://nvidia-isaac-ros.github.io/. But in the last step ,when I running   ros2 launch isaac_ros_apriltag isaac_ros_apriltag_usb_cam.launch.py, there will be errors :
[component_container_mt-1] 2023-12-08 15:28:28.409 ERROR /workspaces/isaac_ros-dev/src/isaac_ros_image_pipeline/isaac_ros_image_proc/gxf/tensorops/extensions/tensorops/components/TensorStream.cpp@104: tensor stream creation failed.
[component_container_mt-1] 2023-12-08 15:28:28.411 ERROR gxf/std/entity_warden.cpp@406: Failed to initialize component 00052 (stream)
[component_container_mt-1] 2023-12-08 15:28:28.412 ERROR gxf/core/runtime.cpp@685: Could not initialize entity 'QAOFSAUKML_resource' (E51): GXF_FAILURE
[component_container_mt-1] 2023-12-08 15:28:28.414 ERROR gxf/std/program.cpp@236: Failed to activate entity 00051 named QAOFSAUKML_resource: GXF_FAILURE
[component_container_mt-1] 2023-12-08 15:28:28.415 ERROR gxf/std/program.cpp@238: Deactivating...
[component_container_mt-1] 2023-12-08 15:28:28.420 ERROR gxf/core/runtime.cpp@1384: Graph activation failed with error: GXF_FAILURE 
and at last 
[ERROR] [1702020508.439103213] [rectify]: [NitrosNode] runGraphAsync Error: GXF_FAILURE
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] runGraphAsync Error: GXF_FAILURE
[ERROR] [component_container_mt-1]: process has died [pid 49742, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args -r __node:=apriltag_container -r __ns:=/'].
I can never start it.

**Comment by jaiveersinghNV** [comment]
Could you provide some more information about your platform?
- x86 or Jetson
- GPU model / Jetson model
- Software version (CUDA version, JetPack version)
- USB camera model name/version

Were you able to run the [AprilTag Quickstart](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_apriltag/isaac_ros_apriltag/index.html#quickstart) prior to trying the USB Camera demo? If not, could you please run the quickstart first? This will help us understand if you're experiencing a problem with AprilTag as a whole or with the USB Camera component specifically.
