### ISSUE TITLE
apriltags will detect but pose data is always NaN

### ISSUE THREAD

**Issue by altineller** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#8]
Hello,

I managed to run isaac_ros_apriltag on docker, and /tag_detection publishes detected tags correctly, but all members of pose data are NaN.

Where can I start to debug this problem.

Best Regards,
Can

**Comment by hemalshahNV** [comment]
It sounds like the camera is not calibrated perhaps? AprilTag detector needs intrinsic parameters (focal length, principal point, etc.) in order to calculate 3D poses from the pixel space tag detections.
